#!/usr/bin/env python3
"""
One-click runner for non-technical users (Claude Cowork / macOS).

Assumes a simple folder layout inside the skill directory:
  exports/  -> raw exports you downloaded (accounts + events)
  config/   -> mapping file (event_type -> interaction_value)
  data/real -> standardized inputs generated by this script
  reports/  -> outputs

Default expected raw files:
  exports/accounts_raw.csv
  exports/events_raw.csv

Run:
  python3 scripts/cowork_one_click.py
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Renewal Radar (Cowork): one-click run")
    p.add_argument("--accounts-raw", default="exports/accounts_raw.csv", help="Raw accounts export CSV")
    p.add_argument("--events-raw", default="exports/events_raw.csv", help="Raw events export CSV")
    p.add_argument(
        "--mapping",
        default="config/renewal_radar_mapping.json",
        help="Mapping JSON (column map + event_type -> interaction_value)",
    )
    p.add_argument("--cutoff", default="auto", help="YYYY-MM-DD or 'auto'")
    p.add_argument("--horizon", type=int, default=30, help="Forecast horizon in days")
    p.add_argument("--risk-threshold", type=float, default=0.5, help="At-risk threshold for churn_prob_end")
    p.add_argument("--no-aggregate-daily", action="store_true", help="Keep one row per event (no daily aggregation)")
    p.add_argument("--open", action="store_true", help="Open the at-risk CSV after running (macOS)")
    return p.parse_args()


def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _run(cmd: list[str]) -> None:
    print(f"$ {' '.join(cmd)}", flush=True)
    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError as e:
        raise SystemExit(f"Command failed (exit {e.returncode}): {' '.join(cmd)}") from e


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    py = sys.executable

    exports_dir = repo_root / "exports"
    config_dir = repo_root / "config"
    real_dir = repo_root / "data" / "real"
    reports_dir = repo_root / "reports"

    _ensure_dir(exports_dir)
    _ensure_dir(config_dir)
    _ensure_dir(real_dir)
    _ensure_dir(reports_dir)

    args = _parse_args()
    accounts_raw = (repo_root / args.accounts_raw).resolve()
    events_raw = (repo_root / args.events_raw).resolve()

    mapping_path = (repo_root / args.mapping).resolve()
    example_mapping = repo_root / "config" / "renewal_radar_mapping.example.json"

    if not accounts_raw.exists():
        available = sorted(p.name for p in exports_dir.glob("*.csv"))
        raise SystemExit(
            f"Missing accounts export: {accounts_raw}\n"
            "Put your CRM/billing accounts export at exports/accounts_raw.csv (or pass --accounts-raw).\n"
            f"CSV files currently in exports/: {available}"
        )
    if not events_raw.exists():
        available = sorted(p.name for p in exports_dir.glob("*.csv"))
        raise SystemExit(
            f"Missing events export: {events_raw}\n"
            "Put your engagement events export at exports/events_raw.csv (or pass --events-raw).\n"
            f"CSV files currently in exports/: {available}"
        )

    if not mapping_path.exists():
        # Best-effort: generate a mapping stub from the exports so users can just tweak.
        inspect = repo_root / "scripts" / "inspect_exports.py"
        if inspect.exists():
            try:
                _run(
                    [
                        py,
                        str(inspect),
                        "--accounts-raw",
                        str(accounts_raw),
                        "--events-raw",
                        str(events_raw),
                        "--write-mapping",
                        str(mapping_path),
                    ]
                )
            except SystemExit as e:
                raise SystemExit(
                    f"{e}\n\n"
                    "Next steps:\n"
                    f"1) Open {mapping_path} and verify column names + event weights\n"
                    "2) Re-run: python3 scripts/cowork_one_click.py"
                ) from e
        elif example_mapping.exists():
            mapping_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(example_mapping, mapping_path)
            print(f"Created default mapping file at {mapping_path}")
            print("Edit it to match your export columns + event types, then re-run.")
        else:
            raise SystemExit(f"Missing mapping file: {mapping_path}")

    prepare = repo_root / "scripts" / "prepare_renewal_radar_inputs.py"
    validate = repo_root / "scripts" / "validate_renewal_radar_inputs.py"
    run = repo_root / "scripts" / "run_renewal_radar.py"

    prepare_cmd = [
        py,
        str(prepare),
        "--accounts-in",
        str(accounts_raw),
        "--events-in",
        str(events_raw),
        "--mapping",
        str(mapping_path),
        "--out-dir",
        str(real_dir),
    ]
    if not args.no_aggregate_daily:
        prepare_cmd.append("--aggregate-daily")

    try:
        _run(prepare_cmd)
    except SystemExit as e:
        raise SystemExit(
            f"{e}\n\n"
            "Preparation failed (usually a column name mismatch).\n"
            "Try:\n"
            f"1) python3 scripts/inspect_exports.py --accounts-raw {accounts_raw} --events-raw {events_raw}\n"
            f"2) Edit {mapping_path}\n"
            "3) Re-run: python3 scripts/cowork_one_click.py"
        ) from e

    try:
        _run(
            [
                py,
                str(validate),
                "--accounts",
                str(real_dir / "accounts.csv"),
                "--touchpoints",
                str(real_dir / "touchpoints.csv"),
            ]
        )
    except SystemExit as e:
        raise SystemExit(
            f"{e}\n\n"
            "Validation failed (bad dates / missing columns / ID mismatches).\n"
            "Fix the exports or mapping, then re-run: python3 scripts/cowork_one_click.py"
        ) from e

    run_cmd = [
        py,
        str(run),
        "--accounts",
        str(real_dir / "accounts.csv"),
        "--touchpoints",
        str(real_dir / "touchpoints.csv"),
        "--cutoff",
        str(args.cutoff),
        "--horizon",
        str(int(args.horizon)),
        "--risk-threshold",
        str(float(args.risk_threshold)),
        "--out-dir",
        str(reports_dir),
    ]
    if args.open:
        run_cmd.append("--open")
    try:
        _run(run_cmd)
    except SystemExit as e:
        raise SystemExit(
            f"{e}\n\n"
            "Forecast run failed. If this is the first time you're running with real data,\n"
            "double-check that accounts.csv and touchpoints.csv share the same account_id values.\n"
            "You can inspect standardized inputs in data/real/."
        ) from e


if __name__ == "__main__":
    main()
