"""Add ab_test_variants table

Revision ID: 9f0017e088a5
Revises: 7bcdc523c6da
Create Date: 2024-10-14 20:53:14.720546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0017e088a5'
down_revision = '7bcdc523c6da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
