#!/bin/bash
# Script 6: Configure Lightning App Builder Guide

echo "=== Configure Lightning App Builder Guide ==="
echo ""
echo "This script provides instructions for configuring the Lightning App Builder"
echo "These steps must be done manually in the Salesforce UI"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. OPEN SALESFORCE:"
echo "   - Navigate to your Salesforce org"
echo "   - URL: https://customer-inspiration-2543.lightning.force.com"
echo ""
echo "2. GO TO SETUP:"
echo "   - Click the gear icon (⚙️) in the top-right"
echo "   - Select 'Setup'"
echo ""
echo "3. NAVIGATE TO OBJECT MANAGER:"
echo "   - In the Quick Find box, type 'Object Manager'"
echo "   - Click on 'Object Manager'"
echo "   - Find and click on 'Opportunity'"
echo ""
echo "4. CREATE/EDIT LIGHTNING RECORD PAGE:"
echo "   - Click on 'Lightning Record Pages'"
echo "   - Look for 'Opportunity Record Page - Three Column'"
echo "   - Click 'Edit' (or create new if it doesn't exist)"
echo ""
echo "5. ENABLE DYNAMIC ACTIONS:"
echo "   - In the Lightning App Builder, find the 'Highlights Panel' component"
echo "   - Click on the Highlights Panel"
echo "   - In properties, check 'Enable Dynamic Actions'"
echo ""
echo "6. ADD THE QUICKBOOKS INVOICE ACTION:"
echo "   - With Highlights Panel selected, click 'Add Action'"
echo "   - In the action list, find 'Create QuickBooks Invoice'"
echo "   - Click to add it"
echo ""
echo "7. CONFIGURE VISIBILITY (OPTIONAL):"
echo "   - Select the 'Create QuickBooks Invoice' action"
echo "   - Click '+ Add Filter' to add visibility rules"
echo "   - Example: Show only when Stage = 'Closed Won'"
echo ""
echo "8. SAVE AND ACTIVATE:"
echo "   - Click 'Save' in the top-right"
echo "   - Click 'Activation' button"
echo "   - Select 'Activate for all users' (or specific profiles)"
echo "   - Click 'Save'"
echo ""
echo "9. ADD REMOTE SITE SETTING:"
echo "   - Go to Setup → Security → Remote Site Settings"
echo "   - Click 'New Remote Site'"
echo "   - Name: QuickBooksMiddleware"
echo "   - URL: http://localhost:3000"
echo "   - Active: Checked"
echo "   - Click 'Save'"
echo ""
echo "10. TEST THE BUTTON:"
echo "    - Navigate to any Opportunity record"
echo "    - You should see 'Create QuickBooks Invoice' in the actions"
echo "    - Click to test"
echo ""
echo "=== TROUBLESHOOTING ==="
echo ""
echo "If the button doesn't appear:"
echo "1. Check if Dynamic Actions is enabled on the Highlights Panel"
echo "2. Verify the LWC was deployed successfully"
echo "3. Check visibility filters if any were added"
echo "4. Ensure you're viewing the correct Lightning Page"
echo "5. Clear browser cache and refresh"
echo ""
echo "If you get API errors:"
echo "1. Verify the middleware is running: http://localhost:3000"
echo "2. Check custom settings configuration"
echo "3. Verify Remote Site Settings"
echo ""
echo "Press Enter when you've completed the configuration..."
read

echo ""
echo "Configuration complete!"
echo "Next step: Run ./7-test-integration.sh"
