#!/bin/bash
# Script I: Configure Lightning Page Instructions

echo "=== Configure Lightning App Builder Guide ==="
echo ""
echo "This script provides instructions for configuring the Lightning App Builder"
echo "These steps must be done manually in the Salesforce UI"
echo ""

# Color codes for better visibility
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${GREEN}Please follow these steps:${NC}"
echo ""
echo -e "${BLUE}1. OPEN SALESFORCE:${NC}"
echo "   - Navigate to your Salesforce org"
echo "   - If needed, use: sf org open --target-org $ORG_ALIAS"
echo ""
echo -e "${BLUE}2. GO TO SETUP:${NC}"
echo "   - Click the gear icon (⚙️) in the top-right"
echo "   - Select 'Setup'"
echo ""
echo -e "${BLUE}3. NAVIGATE TO OBJECT MANAGER:${NC}"
echo "   - In the Quick Find box, type 'Object Manager'"
echo "   - Click on 'Object Manager'"
echo "   - Find and click on 'Opportunity'"
echo ""
echo -e "${BLUE}4. CREATE/EDIT LIGHTNING RECORD PAGE:${NC}"
echo "   - Click on 'Lightning Record Pages' on the left"
echo "   - Look for your current Opportunity page (e.g., 'Opportunity Record Page')"
echo "   - Click 'Edit' (or create new if needed)"
echo ""
echo -e "${BLUE}5. ENABLE DYNAMIC ACTIONS:${NC}"
echo "   - In the Lightning App Builder, find the 'Highlights Panel' component"
echo "   - Click on the Highlights Panel"
echo "   - In the properties pane on the right, check '✓ Enable Dynamic Actions'"
echo ""
echo -e "${BLUE}6. ADD THE QUICKBOOKS INVOICE ACTION:${NC}"
echo "   - With the Highlights Panel still selected"
echo "   - In the properties pane, find 'Actions' section"
echo "   - Click '+ Add Action'"
echo "   - In the action list, find 'Create QuickBooks Invoice'"
echo "   - Click it to add"
echo ""
echo -e "${BLUE}7. CONFIGURE ACTION VISIBILITY (Optional):${NC}"
echo "   - Select the 'Create QuickBooks Invoice' action"
echo "   - Click '+ Add Filter' to add visibility rules"
echo "   - Examples:"
echo "     • Show only when Stage = 'Closed Won'"
echo "     • Hide when QB_Invoice_ID__c is not blank"
echo ""
echo -e "${BLUE}8. ARRANGE ACTIONS (Optional):${NC}"
echo "   - Drag the 'Create QuickBooks Invoice' action to your preferred position"
echo "   - Other actions can be reordered as needed"
echo ""
echo -e "${BLUE}9. SAVE AND ACTIVATE:${NC}"
echo "   - Click 'Save' in the top-right"
echo "   - Click 'Activation...' button"
echo "   - Choose activation options:"
echo "     • Org Default (for all users)"
echo "     • App Default (for specific apps)"
echo "     • App, Record Type, and Profile (for specific profiles)"
echo "   - Click 'Save'"
echo ""
echo -e "${BLUE}10. TEST THE BUTTON:${NC}"
echo "    - Navigate to any Opportunity record"
echo "    - You should see 'Create QuickBooks Invoice' in the action buttons"
echo "    - Click to test the integration"
echo ""
echo -e "${YELLOW}=== TROUBLESHOOTING ===${NC}"
echo ""
echo "If the button doesn't appear:"
echo "1. Check if Dynamic Actions is enabled on the Highlights Panel"
echo "2. Verify the LWC was deployed successfully"
echo "3. Check visibility filters if any were added"
echo "4. Ensure you're viewing the correct Lightning Page"
echo "5. Clear browser cache and refresh"
echo "6. Check user profile has access to the page"
echo ""
echo "If you get API errors when clicking the button:"
echo "1. Verify the middleware is running: http://localhost:3000"
echo "2. Check custom settings configuration (run ./h-configure-settings.sh)"
echo "3. Verify Remote Site Settings is active"
echo "4. Check browser console for detailed errors"
echo ""
echo -e "${GREEN}Press Enter when you've completed the configuration...${NC}"
read

echo ""
echo "✓ Lightning Page configuration complete!"
echo ""
echo "Next step: Run ./j-test-integration.sh"
