"""Add is_active column to partners table

Revision ID: 873205ca49e7
Revises: 2c115acec4ae
Create Date: 2024-10-17 00:30:18.438173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873205ca49e7'
down_revision: Union[str, None] = '2c115acec4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ab_test_variants', sa.Column('model_config', sa.String(length=100), nullable=True))
    op.add_column('ab_test_variants', sa.Column('positive_feedback_count', sa.Integer(), nullable=True))
    op.add_column('ab_test_variants', sa.Column('negative_feedback_count', sa.Integer(), nullable=True))
    op.alter_column('chatbots', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'chatbots', ['telegram_token'])
    op.drop_constraint('chatbots_author_id_fkey', 'chatbots', type_='foreignkey')
    op.create_foreign_key(None, 'chatbots', 'authors', ['author_id'], ['id'])
    op.drop_column('chatbots', 'name')
    op.add_column('partners', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'is_active')
    op.add_column('chatbots', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chatbots', type_='foreignkey')
    op.create_foreign_key('chatbots_author_id_fkey', 'chatbots', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chatbots', type_='unique')
    op.alter_column('chatbots', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ab_test_variants', 'negative_feedback_count')
    op.drop_column('ab_test_variants', 'positive_feedback_count')
    op.drop_column('ab_test_variants', 'model_config')
    # ### end Alembic commands ###
