from dataclasses import dataclass
from typing import List, Tuple, Optional

@dataclass
class WhisperSegment:
    start: float
    end: float
    text: str

class MockWhisperModel:
    """Mock implementation of WhisperModel for testing"""
    def __init__(self, model_size: str = "base", device: str = "cpu"):
        self.model_size = model_size
        self.device = device

    def transcribe(self, audio_path: str, beam_size: int = 5, language: Optional[str] = None) -> Tuple[List[WhisperSegment], dict]:
        """Mock transcription method that returns test data"""
        segments = [
            WhisperSegment(0.0, 2.0, "This is a test transcription."),
            WhisperSegment(2.0, 4.0, "Generated by mock whisper model.")
        ]
        info = {
            "language": language or "en",
            "duration": 4.0,
            "model_size": self.model_size
        }
        return segments, info